n = int(input('Digite um número inteiro qualquer: '))

n1m = (n*1)
n2m = (n*2)
n3m = (n*3)
n4m = (n*4)
n5m = (n*5)
n6m = (n*6)
n7m = (n*7)
n8m = (n*8)
n9m = (n*9)
n10m = (n*10)

print(f'{n}  x  1 = {n1m}')
print(f'{n}  x  2 = {n2m}')
print(f'{n}  x  3 = {n3m}')
print(f'{n}  x  4 = {n4m}')
print(f'{n}  x  5 = {n5m}')
print(f'{n}  x  6 = {n6m}')
print(f'{n}  x  7 = {n7m}')
print(f'{n}  x  8 = {n8m}')
print(f'{n}  x  9 = {n9m}')
print(f'{n}  x  10 = {n10m}')
